app: twitch-tipper-abs
org: mjavala
service: twitch-tipper-abs

provider:

  name: aws

  runtime: nodejs12.x

  stage: dev

  region: us-east-1


functions:
  app:
    handler: index.handler

    events:

      - http: 
        path: /
        method: ANY
        cors: true

      - http:
          path: /{proxy+}
          method: ANY
          cors: true